### ISSUE TITLE
Error loading libkdl-transport-mqueue-gnulinux.so through docker when openGL is enabled

### ISSUE THREAD

**Issue by broesdecat** [orocos/rtt_geometry#22]
Hi,

When running an (etasl) orocos application through docker, kdl_typekit loads without problem when openGL forwarding (so hardware acceleration) is disabled.
However, when the forwarding is enabled (adding  '--device=/dev/dri:/dev/dri \' and '-v=/dev/dri:/dev/dri:rw' to docker run), I get the following error (with shortened paths)

.816 [ ERROR  ][ComponentLoader::import(path_list)] could not load library '<buildpath>/kdl_typekit/lib/orocos/gnulinux/kdl_typekit/types/libkdl-transport-mqueue-gnulinux.so': <buildpath>/kdl_typekit/lib/orocos/gnulinux/kdl_typekit/types/libkdl-transport-mqueue-gnulinux.so: undefined symbol: _ZNK3RTT4base18ChannelElementBase15isRemoteElementEv
0.816 [ ERROR  ][ComponentLoader::import(path_list)] Some found plugins could not be loaded !
0.819 [ ERROR  ][/opt/ros/indigo/bin/rttlua-gnulinux::main()] Exception raised while executing an operation : Some found plugins could not be loaded !
/opt/ros/indigo/bin/rttlua-gnulinux: /opt/ros/indigo/share/lua/5.1/rttlib.lua:762: Operation.call: caught exception 'Unable to complete the operation call. The called operation has thrown an exception'
stack traceback:
	[C]: in function 'op'
	/opt/ros/indigo/share/lua/5.1/rttlib.lua:762: in function 'import'
	...igo/etasl/share/etasl_rtt_examples/custom/deploy.lua:22: in function 'initializePackages'
	...igo/etasl/share/etasl_rtt_examples/custom/deploy.lua:152: in function 'deploy'
	...igo/etasl/share/etasl_rtt_examples/custom/deploy.lua:199: in main chunk

Do I have to compile kdl differently when openGL will be used?

Best,
Broes

**Comment by meyerj** [comment]
Hmm, sounds strange. The symbol `_ZNK3RTT4base18ChannelElementBase15isRemoteElementEv` is defined in the core `liborocos-rtt-gnulinux.so` and should be already defined at the time the ComponentLoader loads the plugin. I do not see a relationship to OpenGL here, but I am not familiar with the [Direct Rendering Manager](https://en.wikipedia.org/wiki/Direct_Rendering_Manager).

Is the content of both containers really the same or could it be that due to some mount options you mixed different ABI-incompatible versions of RTT and the kdl_typekit plugin library? The symbol `RTT::base::ChannelElementBase::isRemoteElement` is present in master and toolchain-2.9 of RTT, but not in toolchain-2.8. So if you compiled RTT from source with one of the newer branches, you also have to compile all dependent typekit and component libraries from source against the same version. For the case you have a ROS installation on your system with `ros-indigo-rtt` installed (which is based on toolchain-2.8) and compile dependent packages from source, even against a newer version of RTT installed at some other location, you should uninstall `ros-indigo-rtt` or you cannot be sure that they pick up the older headers installed in `/opt/ros/indigo/include` alongside some other ROS dependencies.

We also used OpenGL in Docker containers in the past without any issues and without mounting `/dev/dri` (by providing the correct version of `libGL.so` only), but that was with the nvidia proprietary drivers and things might be different depending on the driver in use.
